template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "tigr1271"
__REPO__ = "lang-tir"
__UND2C__ = "ti"
__UNDEFINED__ = "Tigrinya"
__UND__ = "tir"
