template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "tigr1271"
__REPO__ = "lang-tir"
__UND2C__ = "ti"
__UNDEFINED__ = "Tigrinya"
__UND__ = "tir"
