[package]
name = "tir"
human_name = "Tigrinya"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.tir]
filename = "ti-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-tir"
platform = "windows"
uuid = "110999CA-5C5F-491E-A8AC-9D4331606B66"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.ti"
package = "speller-tir"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-tir-mso"
platform = "windows"
uuid = "98CC400E-6960-4B34-92F5-DC5127B23AB4"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-tir"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
